### ISSUE TITLE
EnumToString.fromString does not work with String that include hyphen

### ISSUE THREAD

**Issue by geek-sajjad** [rknell/flutterEnumsToString#16]
Hi I use your package in my project , but i have this problem : 

```
status: EnumToString.fromString(TicketStatus.values, json["status"]),

enum TicketStatus {
  open,
  customerReply,
}

```
and my REST API return `"status": "Customer-Reply",`
and i can't use hyphen in the Enum values ! what can i do ??

**Comment by rknell** [comment]
Hey @geek-sajjad 

Right now there isn't a way. The other open ticket is also about the same thing so there is definitely a need for it. Unfortunately I have had the flood gates open since covid has cleared up near me to haven't had time - or an incident that has caused me to write it.

feel free to jump over to #15 to discuss the best way to implement it. The big hold up is that its not a global singleton and doesn't hold a state, so you need to store the mapping somehow.

Ideally I would like something like in JSON serializable which has the fieldRename parameter which handles camelcase, snake and skewer case, but your example with the uppercase first letter wouldn't work there either.

**Comment by geek-sajjad** [comment]
thank you for your responding , i solved with this way : 


```
final EnumValues<TicketStatus> ticketStatusValues =
    EnumValues<TicketStatus>(<String, TicketStatus>{
  'Open': TicketStatus.open,
  'Customer-Reply': TicketStatus.customerReply,
});

class EnumValues<T> {
  Map<String, T> map;
  Map<T, String> reverseMap;

  EnumValues(this.map);

  Map<T, String> get reverse {
    if (reverseMap == null) {
      reverseMap = map.map((k, v) => new MapEntry(v, k));
    }
    return reverseMap;
  }
}

enum TicketStatus {
  open,
  customerReply,
}


Ticket.fromJson(Map<String, dynamic> json) {
   return Ticket(
      status: ticketStatusValues.map[json["status"]],
    );
}

```

**Comment by rknell** [comment]
Closing as we will deal with this in #15
